### ISSUE TITLE
Make does not work

### ISSUE THREAD

**Issue by pinceladasdaweb** [jonataswalker/es6-sample-project#54]
Hello Jonatas,

I was taking a look at your project and found it very interesting, only to make some tests here, just not working.

![captura de tela 2016-11-06 as 12 08 12](https://cloud.githubusercontent.com/assets/814325/20038380/c4e9e0c0-a419-11e6-8979-dea210b4a63b.png)

To run any command with Make, I have the above error.

**Comment by jonataswalker** [comment]
Hey @pinceladasdaweb I've just ran it here and it's all ok.

![es6-project-kate_001](https://cloud.githubusercontent.com/assets/10571881/20051685/76ec8640-a4b7-11e6-9f9b-2de8f175ff52.png)

**Comment by jonataswalker** [comment]
Are you using Mac?

**Comment by pinceladasdaweb** [comment]
Yes @jonataswalker.

**Comment by jonataswalker** [comment]
@pinceladasdaweb 

Please try changing in Makefile:

``` shell
NOW     := $(shell date --iso=seconds)
```

To:

``` shell
NOW     := $(shell date +%FT%T%z)
```

**Comment by pinceladasdaweb** [comment]
Thank you very much @jonataswalker. Now it is working ok.
